---
version: '3.2'

networks:
  infra_default:
    external: true
  st_network:
    external: true

services:
  # postgresql:
  #   image: postgres:9.6
  #   hostname: stackoverflow_data-postgresql
  #   networks:
  #     st_network:
  #       aliases:
  #         - stackoverflow_data-postgresql
  #   command: postgres -c max_connections=300
  #   environment:
  #     - POSTGRES_DB=stackoverflow_data
  #     - POSTGRES_USER=stackoverflow_data
  #     - POSTGRES_PASSWORD=stackoverflow_data
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432

  app:
    build:
      context: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - ./media_root:/usr/src/media_root
      - ./static_root:/usr/src/static_root
    environment:
      # - DB_NAME=stackoverflow_data
      # - DB_USER=stackoverflow_data
      # - DB_HOST=stackoverflow_data-postgresql
      # - DB_PASSWORD=stackoverflow_data
      # - DB_PORT=5432
      - DEBUG='true'
    restart: unless-stopped
    hostname: stackoverflow_data-app
    networks:
      infra_default:
        aliases:
          - stackoverflow_data-app
      st_network:
        aliases:
          - stackoverflow_data-app
    ports:
      - 8000:8000
    # depends_on:
    #   - postgresql
